title: Yay.se
author:
  name: Olof Brickarp
  email: 'olle@yay.se'
metadata:
    description: 'Webbdesigner/front-end-utvecklaren Olof Brickarp'

bio: 'Detta är en svensk bio'
bio_en: 'Olof Brickarp is a digital designer / front-end developer currently living in Gothenburg, Sweden. '
